#ifndef BEER_PROTO_H_INCLUDED
#define BEER_PROTO_H_INCLUDED

/*
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * 1. Redistributions of source code must retain the above
 *    copyright notice, this list of conditions and the
 *    following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY <COPYRIGHT HOLDER> ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * <COPYRIGHT HOLDER> OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
 * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/**
 * \file beer_proto.h
 * \brief IProto protocol constants
 */

/**
 * \brief Request/response header field types (keys)
 */
enum beer_header_key_t {
	BEER_CODE      = 0x00,
	BEER_SYNC      = 0x01,
	BEER_SERVER_ID = 0x02,
	BEER_LSN       = 0x03,
	BEER_TIMESTAMP = 0x04,
	BEER_SCHEMA_ID = 0x05
};

/**
 * \brief Request body field types (keys)
 */
enum beer_body_key_t {
	BEER_SPACE = 0x10,
	BEER_INDEX = 0x11,
	BEER_LIMIT = 0x12,
	BEER_OFFSET = 0x13,
	BEER_ITERATOR = 0x14,
	BEER_INDEX_BASE = 0x15,
	BEER_KEY = 0x20,
	BEER_TUPLE = 0x21,
	BEER_FUNCTION = 0x22,
	BEER_USERNAME = 0x23,
	BEER_SERVER_UUID = 0x24,
	BEER_CLUSTER_UUID = 0x25,
	BEER_VCLOCK = 0x26,
	BEER_EXPRESSION = 0x27,
	BEER_OPS = 0x28,

};

/**
 * \brief Response body field types (keys)
 */
enum beer_response_key_t {
	BEER_DATA = 0x30,
	BEER_ERROR = 0x31
};

/**
 * \brief Request types
 */
enum beer_request_t {
	BEER_OP_SELECT    = 1,
	BEER_OP_INSERT    = 2,
	BEER_OP_REPLACE   = 3,
	BEER_OP_UPDATE    = 4,
	BEER_OP_DELETE    = 5,
	BEER_OP_CALL_16   = 6,
	BEER_OP_AUTH      = 7,
	BEER_OP_EVAL      = 8,
	BEER_OP_UPSERT    = 9,
	BEER_OP_CALL      = 10,
	BEER_OP_PING      = 64,
	BEER_OP_JOIN      = 65,
	BEER_OP_SUBSCRIBE = 66
};

/**
 * \brief Update operations
 */
enum beer_update_op_t {
	BEER_UOP_ADDITION = '+',
	BEER_UOP_SUBSTRACT = '-',
	BEER_UOP_AND = '&',
	BEER_UOP_XOR = '^',
	BEER_UOP_OR = '|',
	BEER_UOP_DELETE = '#',
	BEER_UOP_INSERT = '!',
	BEER_UOP_ASSIGN = '=',
	BEER_UOP_SPLICE = ':',
};

/**
 * \brief Iterator types
 */
enum beer_iterator_t {
	BEER_ITER_EQ = 0,
	BEER_ITER_REQ,
	BEER_ITER_ALL,
	BEER_ITER_LT,
	BEER_ITER_LE,
	BEER_ITER_GE,
	BEER_ITER_GT,
	BEER_ITER_BITS_ALL_SET,
	BEER_ITER_BITS_ANY_SET,
	BEER_ITER_BITS_ALL_NOT_SET,
	BEER_ITER_OVERLAP,
	BEER_ITER_NEIGHBOR,
};

/**
 * \internal
 */
#define BEER_SCRAMBLE_SIZE 20
/**
 * \internal
 */
#define BEER_GREETING_SIZE 128
/**
 * \internal
 */
#define BEER_VERSION_SIZE  64
/**
 * \internal
 */
#define BEER_SALT_SIZE     44

/**
 * \brief System spaces
 */
enum beer_spaces_t {
	beer_sp_space = 280,
	beer_sp_index = 288,
	beer_sp_func  = 296,
	beer_sp_user  = 304,
	beer_sp_priv  = 312,
	beer_vsp_space = 281,
	beer_vsp_index = 289,
	beer_vsp_func  = 297,
	beer_vsp_user  = 305,
	beer_vsp_priv  = 313,
};

/**
 * \brief System indexes
 */
enum beer_indexes_t {
	beer_vin_primary = 0,
	beer_vin_owner   = 1,
	beer_vin_name    = 2,
};

/**
 * \brief Error code types
 */
enum beer_errcode_t {
	BEER_ER_UNKNOWN = 0,
	BEER_ER_ILLEGAL_PARAMS = 1,
	BEER_ER_MEMORY_ISSUE = 2,
	BEER_ER_TUPLE_FOUND = 3,
	BEER_ER_TUPLE_NOT_FOUND = 4,
	BEER_ER_UNSUPPORTED = 5,
	BEER_ER_NONMASTER = 6,
	BEER_ER_READONLY = 7,
	BEER_ER_INJECTION = 8,
	BEER_ER_CREATE_SPACE = 9,
	BEER_ER_SPACE_EXISTS = 10,
	BEER_ER_DROP_SPACE = 11,
	BEER_ER_ALTER_SPACE = 12,
	BEER_ER_INDEX_TYPE = 13,
	BEER_ER_MODIFY_INDEX = 14,
	BEER_ER_LAST_DROP = 15,
	BEER_ER_TUPLE_FORMAT_LIMIT = 16,
	BEER_ER_DROP_PRIMARY_KEY = 17,
	BEER_ER_KEY_PART_TYPE = 18,
	BEER_ER_EXACT_MATCH = 19,
	BEER_ER_INVALID_MSGPACK = 20,
	BEER_ER_PROC_RET = 21,
	BEER_ER_TUPLE_NOT_ARRAY = 22,
	BEER_ER_FIELD_TYPE = 23,
	BEER_ER_FIELD_TYPE_MISMATCH = 24,
	BEER_ER_SPLICE = 25,
	BEER_ER_ARG_TYPE = 26,
	BEER_ER_TUPLE_IS_TOO_LONG = 27,
	BEER_ER_UNKNOWN_UPDATE_OP = 28,
	BEER_ER_UPDATE_FIELD = 29,
	BEER_ER_FIBER_STACK = 30,
	BEER_ER_KEY_PART_COUNT = 31,
	BEER_ER_PROC_LUA = 32,
	BEER_ER_NO_SUCH_PROC = 33,
	BEER_ER_NO_SUCH_TRIGGER = 34,
	BEER_ER_NO_SUCH_INDEX = 35,
	BEER_ER_NO_SUCH_SPACE = 36,
	BEER_ER_NO_SUCH_FIELD = 37,
	BEER_ER_SPACE_FIELD_COUNT = 38,
	BEER_ER_INDEX_FIELD_COUNT = 39,
	BEER_ER_WAL_IO = 40,
	BEER_ER_MORE_THAN_ONE_TUPLE = 41,
	BEER_ER_ACCESS_DENIED = 42,
	BEER_ER_CREATE_USER = 43,
	BEER_ER_DROP_USER = 44,
	BEER_ER_NO_SUCH_USER = 45,
	BEER_ER_USER_EXISTS = 46,
	BEER_ER_PASSWORD_MISMATCH = 47,
	BEER_ER_UNKNOWN_REQUEST_TYPE = 48,
	BEER_ER_UNKNOWN_SCHEMA_OBJECT = 49,
	BEER_ER_CREATE_FUNCTION = 50,
	BEER_ER_NO_SUCH_FUNCTION = 51,
	BEER_ER_FUNCTION_EXISTS = 52,
	BEER_ER_FUNCTION_ACCESS_DENIED = 53,
	BEER_ER_FUNCTION_MAX = 54,
	BEER_ER_SPACE_ACCESS_DENIED = 55,
	BEER_ER_USER_MAX = 56,
	BEER_ER_NO_SUCH_ENGINE = 57,
	BEER_ER_RELOAD_CFG = 58,
	BEER_ER_CFG = 59,
	BEER_ER_SOPHIA = 60,
	BEER_ER_LOCAL_SERVER_IS_NOT_ACTIVE = 61,
	BEER_ER_UNKNOWN_SERVER = 62,
	BEER_ER_CLUSTER_ID_MISMATCH = 63,
	BEER_ER_INVALID_UUID = 64,
	BEER_ER_CLUSTER_ID_IS_RO = 65,
	BEER_ER_RESERVED66 = 66,
	BEER_ER_SERVER_ID_IS_RESERVED = 67,
	BEER_ER_INVALID_ORDER = 68,
	BEER_ER_MISSING_REQUEST_FIELD = 69,
	BEER_ER_IDENTIFIER = 70,
	BEER_ER_DROP_FUNCTION = 71,
	BEER_ER_ITERATOR_TYPE = 72,
	BEER_ER_REPLICA_MAX = 73,
	BEER_ER_INVALID_XLOG = 74,
	BEER_ER_INVALID_XLOG_NAME = 75,
	BEER_ER_INVALID_XLOG_ORDER = 76,
	BEER_ER_NO_CONNECTION = 77,
	BEER_ER_TIMEOUT = 78,
	BEER_ER_ACTIVE_TRANSACTION = 79,
	BEER_ER_NO_ACTIVE_TRANSACTION = 80,
	BEER_ER_CROSS_ENGINE_TRANSACTION = 81,
	BEER_ER_NO_SUCH_ROLE = 82,
	BEER_ER_ROLE_EXISTS = 83,
	BEER_ER_CREATE_ROLE = 84,
	BEER_ER_INDEX_EXISTS = 85,
	BEER_ER_TUPLE_REF_OVERFLOW = 86,
	BEER_ER_ROLE_LOOP = 87,
	BEER_ER_GRANT = 88,
	BEER_ER_PRIV_GRANTED = 89,
	BEER_ER_ROLE_GRANTED = 90,
	BEER_ER_PRIV_NOT_GRANTED = 91,
	BEER_ER_ROLE_NOT_GRANTED = 92,
	BEER_ER_MISSING_SNAPSHOT = 93,
	BEER_ER_CANT_UPDATE_PRIMARY_KEY = 94,
	BEER_ER_UPDATE_INTEGER_OVERFLOW = 95,
	BEER_ER_GUEST_USER_PASSWORD = 96,
	BEER_ER_TRANSACTION_CONFLICT = 97,
	BEER_ER_UNSUPPORTED_ROLE_PRIV = 98,
	BEER_ER_LOAD_FUNCTION = 99,
	BEER_ER_FUNCTION_LANGUAGE = 100,
	BEER_ER_RTREE_RECT = 101,
	BEER_ER_PROC_C = 102,
	BEER_ER_UNKNOWN_RTREE_INDEX_DISTANCE_TYPE = 103,
	BEER_ER_PROTOCOL = 104,
	BEER_ER_UPSERT_UNIQUE_SECONDARY_KEY = 105,
	BEER_ER_WRONG_INDEX_RECORD = 106,
	BEER_ER_WRONG_INDEX_PARTS = 107,
	BEER_ER_WRONG_INDEX_OPTIONS = 108,
	BEER_ER_WRONG_SCHEMA_VERSION = 109,
	BEER_ER_SLAB_ALLOC_MAX = 110,
};

#endif /* BEER_PROTO_H_INCLUDED */
